### ISSUE TITLE
Change Binding Post Spacing to 19mm

### ISSUE THREAD

**Issue by mobilinkd** [benkrasnow/MakitaBatteryPowerSupply#1]
Standard binding post spacing is 3/4" (19.05mm).  The binding posts in the current model appears to be about 34mm.  Changing the spacing to the standard used for bench PSUs would allow use of dual-binding post adapters.

**Comment by benkrasnow** [comment]
I added step and stl files with 19mm spacing. I actually intended the original wider spacing because I've only ever used dual-banana connectors extremely rarely, but have often bumped my fingers into the neighboring terminal.  Anyway, it's good to have choices!
